### ISSUE TITLE
Cluster

### ISSUE THREAD

**Issue by gedw99** [history-engine/engine#5]
If you want to cluster, we can just use NATS Jetstream in front and have all Set requests be forward to all the Zinc Servers ( etc ) 

For a Get, just use a NATS Queue pattern and it will hit one of the Zinc Servers.

NATS Jetstream can keep track of all Zinc Servers, by just wrapping Zinc with nats.go.

NATS can also run jobs, and makes redis not needed.
https://github.com/choria-io/asyncjobs

**Comment by fengqi** [comment]
OK
